import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { MetricCard, PillButton, SectionLabel } from '@/components/FitTrackUI';

export default function HomeScreen() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 102 }]} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.mutedForeground }]}>MONDAY, AUGUST 24</Text><Text style={[styles.greeting, { color: colors.foreground }]}>Good morning, Alex</Text></View><Pressable testID="profile-button" style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.avatarText, { color: colors.secondaryForeground }]}>A</Text></Pressable></View>
    <View style={[styles.recoveryCard, { backgroundColor: colors.primary }]}><View style={styles.recoveryCopy}><SectionLabel>Today's readiness</SectionLabel><Text style={[styles.recoveryTitle, { color: colors.primaryForeground }]}>You’re ready to move</Text><Text style={[styles.recoverySub, { color: '#A5B6AB' }]}>Your body is responding well to your recent training.</Text></View><View style={[styles.scoreRing, { borderColor: colors.accent }]}><Text style={[styles.score, { color: colors.primaryForeground }]}>82</Text><Text style={[styles.scoreUnit, { color: '#A5B6AB' }]}>/100</Text></View></View>
    <View style={styles.sectionHeader}><SectionLabel>Today at a glance</SectionLabel><Feather name="more-horizontal" size={21} color={colors.mutedForeground} /></View>
    <View style={styles.metrics}><MetricCard icon="activity" label="Steps" value="7,842" detail="78% of daily goal" tone="lime" /><MetricCard icon="heart" label="Heart rate" value="68" unit=" BPM" detail="Resting average" tone="dark" /><MetricCard icon="moon" label="Sleep" value="7h 42m" detail="92% sleep score" /><MetricCard icon="zap" label="Calories" value="1,840" unit=" kcal" detail="Active burn" /></View>
    <View style={styles.sectionHeader}><SectionLabel>Suggested for you</SectionLabel><Text style={[styles.link, { color: colors.success }]}>See all</Text></View>
    <View style={[styles.workoutCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.workoutIcon, { backgroundColor: colors.secondary }]}><Feather name="trending-up" size={21} color={colors.success} /></View><View style={styles.workoutCopy}><Text style={[styles.workoutTitle, { color: colors.cardForeground }]}>Upper body strength</Text><Text style={[styles.workoutMeta, { color: colors.mutedForeground }]}>50 min  ·  Moderate intensity</Text></View><Feather name="chevron-right" size={20} color={colors.mutedForeground} /></View>
    <PillButton icon="play" label="Start workout" filled />
    <Text style={[styles.demo, { color: colors.mutedForeground }]}>DEMO DATA · Connect Health Connect to sync real metrics</Text>
  </ScrollView>;
}

const styles = StyleSheet.create({ content: { paddingHorizontal: 20, gap: 22 }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, eyebrow: { fontSize: 11, fontWeight: '700', letterSpacing: 1.2, marginBottom: 7 }, greeting: { fontSize: 27, fontWeight: '700', letterSpacing: -0.8 }, avatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontWeight: '700', fontSize: 16 }, recoveryCard: { borderRadius: 24, padding: 21, flexDirection: 'row', alignItems: 'center', minHeight: 174 }, recoveryCopy: { flex: 1, gap: 10 }, recoveryTitle: { fontSize: 22, fontWeight: '700', letterSpacing: -0.4 }, recoverySub: { fontSize: 13, lineHeight: 19, maxWidth: 200 }, scoreRing: { width: 101, height: 101, borderRadius: 51, borderWidth: 7, alignItems: 'center', justifyContent: 'center', marginLeft: 12 }, score: { fontSize: 30, fontWeight: '700', lineHeight: 33 }, scoreUnit: { fontSize: 12, fontWeight: '600' }, sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, metrics: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', gap: 10 }, link: { fontSize: 13, fontWeight: '700' }, workoutCard: { borderRadius: 18, borderWidth: 1, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 13 }, workoutIcon: { width: 46, height: 46, borderRadius: 15, alignItems: 'center', justifyContent: 'center' }, workoutCopy: { flex: 1, gap: 5 }, workoutTitle: { fontSize: 15, fontWeight: '700' }, workoutMeta: { fontSize: 12 }, demo: { textAlign: 'center', fontSize: 10, letterSpacing: 0.6, lineHeight: 15, marginTop: -8 } });