import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Feather } from '@expo/vector-icons';
import { useColors } from '@/hooks/useColors';
import { healthConnectManager, HealthSummary } from '@/data/health/HealthConnectManager';
import { MetricCard, PillButton, SectionLabel } from '@/components/FitTrackUI';

const formatSleep = (minutes: number | null) => minutes === null ? '—' : `${Math.floor(minutes / 60)}h ${minutes % 60}m`;
const formatNumber = (value: number | null) => value === null ? '—' : Math.round(value).toLocaleString();
export default function HomeScreen() {
  const colors = useColors(); const insets = useSafeAreaInsets(); const [summary, setSummary] = React.useState<HealthSummary | null>(null);
  React.useEffect(() => { healthConnectManager.readToday().then(setSummary); }, []);
  const connected = summary?.status === 'connected';
  return <ScrollView style={{ backgroundColor: colors.background }} contentContainerStyle={[styles.content, { paddingTop: insets.top + 18, paddingBottom: insets.bottom + 102 }]} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.mutedForeground }]}>MONDAY, AUGUST 24</Text><Text style={[styles.greeting, { color: colors.foreground }]}>Good morning, Alex</Text></View><Pressable testID="profile-button" style={[styles.avatar, { backgroundColor: colors.secondary }]}><Text style={[styles.avatarText, { color: colors.secondaryForeground }]}>A</Text></Pressable></View>
    <View style={[styles.recoveryCard, { backgroundColor: colors.primary }]}><View style={styles.recoveryCopy}><SectionLabel>Today's readiness</SectionLabel><Text style={[styles.recoveryTitle, { color: colors.primaryForeground }]}>{connected ? 'Health data is synced' : 'Connect your health data'}</Text><Text style={[styles.recoverySub, { color: '#A5B6AB' }]}>{connected ? 'Your daily metrics are coming from Health Connect.' : 'Allow Health Connect access to calculate readiness from your real activity.'}</Text></View><View style={[styles.scoreRing, { borderColor: colors.accent }]}><Text style={[styles.score, { color: colors.primaryForeground }]}>{connected ? '—' : '—'}</Text><Text style={[styles.scoreUnit, { color: '#A5B6AB' }]}>/100</Text></View></View>
    <View style={styles.sectionHeader}><SectionLabel>Today at a glance</SectionLabel><Feather name="refresh-cw" size={17} color={colors.mutedForeground} /></View>
    <View style={styles.metrics}><MetricCard icon="activity" label="Steps" value={formatNumber(summary?.steps ?? null)} detail={connected ? 'From Health Connect' : 'Waiting for permission'} tone="lime" /><MetricCard icon="heart" label="Heart rate" value={formatNumber(summary?.heartRate ?? null)} unit={summary?.heartRate ? ' BPM' : ''} detail="Latest available" tone="dark" /><MetricCard icon="moon" label="Sleep" value={formatSleep(summary?.sleepMinutes ?? null)} detail="Last recorded session" /><MetricCard icon="zap" label="Calories" value={formatNumber(summary?.calories ?? null)} unit={summary?.calories ? ' kcal' : ''} detail="Active burn" /></View>
    {!connected ? <View style={[styles.connectCard, { backgroundColor: colors.secondary }]}><Feather name="shield" size={19} color={colors.success} /><View style={styles.connectCopy}><Text style={[styles.connectTitle, { color: colors.foreground }]}>No real health data yet</Text><Text style={[styles.connectSub, { color: colors.mutedForeground }]}>Connect Health Connect from Profile on an Android development build.</Text></View></View> : <Text style={[styles.synced, { color: colors.mutedForeground }]}>Last synced {summary?.lastSyncedAt ? new Date(summary.lastSyncedAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' }) : '—'}</Text>}
    <View style={styles.sectionHeader}><SectionLabel>Suggested for you</SectionLabel><Text style={[styles.link, { color: colors.success }]}>See all</Text></View><View style={[styles.workoutCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.workoutIcon, { backgroundColor: colors.secondary }]}><Feather name="trending-up" size={21} color={colors.success} /></View><View style={styles.workoutCopy}><Text style={[styles.workoutTitle, { color: colors.cardForeground }]}>Upper body strength</Text><Text style={[styles.workoutMeta, { color: colors.mutedForeground }]}>50 min  ·  Moderate intensity</Text></View><Feather name="chevron-right" size={20} color={colors.mutedForeground} /></View><PillButton icon="play" label="Start workout" filled />
  </ScrollView>;
}
const styles = StyleSheet.create({ content:{paddingHorizontal:20,gap:22},header:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{fontSize:11,fontWeight:'700',letterSpacing:1.2,marginBottom:7},greeting:{fontSize:27,fontWeight:'700',letterSpacing:-0.8},avatar:{width:42,height:42,borderRadius:21,alignItems:'center',justifyContent:'center'},avatarText:{fontWeight:'700',fontSize:16},recoveryCard:{borderRadius:24,padding:21,flexDirection:'row',alignItems:'center',minHeight:174},recoveryCopy:{flex:1,gap:10},recoveryTitle:{fontSize:22,fontWeight:'700',letterSpacing:-0.4},recoverySub:{fontSize:13,lineHeight:19,maxWidth:200},scoreRing:{width:101,height:101,borderRadius:51,borderWidth:7,alignItems:'center',justifyContent:'center',marginLeft:12},score:{fontSize:30,fontWeight:'700',lineHeight:33},scoreUnit:{fontSize:12,fontWeight:'600'},sectionHeader:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},metrics:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between',gap:10},link:{fontSize:13,fontWeight:'700'},connectCard:{borderRadius:18,padding:15,flexDirection:'row',alignItems:'center',gap:12},connectCopy:{flex:1,gap:4},connectTitle:{fontSize:14,fontWeight:'700'},connectSub:{fontSize:12,lineHeight:17},synced:{fontSize:11,textAlign:'center'},workoutCard:{borderRadius:18,borderWidth:1,padding:15,flexDirection:'row',alignItems:'center',gap:13},workoutIcon:{width:46,height:46,borderRadius:15,alignItems:'center',justifyContent:'center'},workoutCopy:{flex:1,gap:5},workoutTitle:{fontSize:15,fontWeight:'700'},workoutMeta:{fontSize:12}});